# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Commond(object):
    def setupUi(self, Commond):
        Commond.setObjectName("Commond")
        Commond.resize(738, 495)
        self.centralwidget = QtWidgets.QWidget(Commond)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 2)
        Commond.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Commond)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 26))
        self.menubar.setObjectName("menubar")
        Commond.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Commond)
        self.statusbar.setObjectName("statusbar")
        Commond.setStatusBar(self.statusbar)

        self.retranslateUi(Commond)
        QtCore.QMetaObject.connectSlotsByName(Commond)

    def retranslateUi(self, Commond):
        _translate = QtCore.QCoreApplication.translate
        Commond.setWindowTitle(_translate("Commond", "命令执行"))
        self.pushButton.setText(_translate("Commond", "执行"))



if  __name__=="__main__":
    app=QtWidgets.QApplication(sys.argv)
    widget= QtWidgets.QMainWindow()
    ui= Ui_Commond()
    ui.setupUi(widget)
    widget.setWindowIcon(QtGui.QIcon(":/logo.png"))
    widget.show()
    sys.exit(app.exec_())